"""Generate docs/tasks.md — the task inventory + how-to-run, from each task's
spec.json (distribution metadata) and results/per_task.csv (rewards).

    venv/bin/python scripts/make_task_inventory.py
"""

from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

HARBOR = Path("website-rl-eval-harbor")
TIER_ORDER = {"easy": 0, "medium": 1, "hard": 2}


def short(s: str, n: int = 38) -> str:
    s = s.split(" — ")[0].split(",")[0].strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def main() -> None:
    rewards = {}
    with open("results/per_task.csv") as f:
        for r in csv.DictReader(f):
            rewards[r["task"]] = (r["reward_mean"], r["reward_std"], r["n_trials"])

    rows = []
    site_types, aesthetics = Counter(), Counter()
    for spec_path in HARBOR.glob("eval-*/.build/site/spec.json"):
        task = spec_path.parts[-4]
        if task not in rewards:
            continue
        spec = json.loads(spec_path.read_text())
        pages = len(list((HARBOR / task / "tests/reference").glob("*.png")))
        site_types[short(spec["site_type"], 60)] += 1
        aesthetics[short(spec["aesthetic"], 60)] += 1
        rm, rs, n = rewards[task]
        rows.append({
            "task": task, "seed": spec["seed"], "tier": spec["difficulty"],
            "pages": pages, "site_type": short(spec["site_type"]),
            "aesthetic": short(spec["aesthetic"]), "layout": short(spec["layout"], 26),
            "reward": f"{float(rm):.3f}±{float(rs):.3f}", "n": n,
        })
    rows.sort(key=lambda r: (TIER_ORDER[r["tier"]], -float(r["reward"].split("±")[0])))

    lines = []
    lines.append("# Task inventory\n")
    lines.append(f"**{len(rows)} tasks** generated by the pipeline (`build_task.sh <seed> "
                 "<easy|medium|hard>`), every one built on the in-image font pipeline so its "
                 "reference is reachable by the agent. Each is a self-contained Harbor task.\n")
    e = sum(r["tier"] == "easy" for r in rows)
    m = sum(r["tier"] == "medium" for r in rows)
    h = sum(r["tier"] == "hard" for r in rows)
    lines.append(f"**Distribution:** {e} easy · {m} medium · {h} hard (tail-weighted). "
                 f"All ≥5 pages. Mean reward by tier and full results in "
                 f"[`evaluation.md`](evaluation.md).\n")

    lines.append("## Variety (the generator samples orthogonal axes per seed — see "
                 "[`../ideas.md`](../ideas.md) I6)\n")
    lines.append("**Site types:** " + ", ".join(f"{k} ({v})" for k, v in site_types.most_common()) + "\n")
    lines.append("**Aesthetics:** " + ", ".join(f"{k} ({v})" for k, v in aesthetics.most_common()) + "\n")

    lines.append("## The tasks\n")
    lines.append("| task | tier | pages | site type | aesthetic | layout | reward (mean±std, n) |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(f"| `{r['task']}` | {r['tier']} | {r['pages']} | {r['site_type']} | "
                     f"{r['aesthetic']} | {r['layout']} | {r['reward']} ({r['n']}) |")

    lines.append("\n## How to run a task\n")
    lines.append("Each task dir holds `task.toml`, `instruction.md`, `environment/` (Dockerfile + "
                 "agent input screenshots + grader code), `tests/` (verifier + hidden reference), "
                 "and `solution/` (oracle).\n")
    lines.append("```bash")
    lines.append("# from inside a task dir — runs Opus 4.7, scores it, writes the reward")
    lines.append("cd website-rl-eval-harbor/eval-pear-easy")
    lines.append("../../venv/bin/harbor run -c run.agent.yaml      # environment.type: modal")
    lines.append("# local Docker instead of Modal:")
    lines.append("HARBOR_ENV_TYPE=docker ../../venv/bin/harbor run -c run.agent.yaml")
    lines.append("# validate the grader ceiling (oracle ≈ 1.0):")
    lines.append("../../venv/bin/harbor run -c run.oracle.yaml")
    lines.append("```\n")
    lines.append("> The raw per-trial job outputs (agent trajectories + renders) are large and "
                 "git-ignored; the distilled rewards + per-dimension scores live in "
                 "[`../results/`](../results/).")

    Path("docs/tasks.md").write_text("\n".join(lines) + "\n")
    print(f"wrote docs/tasks.md ({len(rows)} tasks: {e} easy / {m} medium / {h} hard)")


if __name__ == "__main__":
    main()
